### ISSUE TITLE
SyntaxError: Unexpected token '??=' while attempt to execute any minity command.

### ISSUE THREAD

**Issue by nathan130200** [minity-script/minity#24]
```cs
C:\Users\natha\AppData\Local\Yarn\Data\global\node_modules\minity\bin\Project.js:349
    buildDirectory??=this.buildDirectory;
                  ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\natha\AppData\Local\Yarn\Data\global\node_modules\minity\bin\commands.js:2:46)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)```

Using minity@latest as recommended by docs.

**Comment by nathan130200** [comment]
Need set in README, that requires Node 15 and newer
